# Generated by Django 4.2.1 on 2023-05-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0006_rename_longdescription_pizza_long_description'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Pizza', 'Pizza'), ('SpecialOffer', 'Special Offer'), ('LunchOffer', 'Lunch Offer'), ('TwoForOne', 'Two for One')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('lunch_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.lunchoffer')),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
                ('special_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.specialoffer')),
                ('two_for_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.twoforone')),
            ],
        ),
    ]
