# Generated by Django 4.2.1 on 2023-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_cart_items_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cartitem_set', to='cart.cart'),
        ),
    ]
