# Generated by Django 4.2 on 2023-05-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='priceLarge',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='priceMedium',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='priceSmall',
        ),
    ]
