# Generated by Django 4.2.1 on 2023-05-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_pricelarge_pizza_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='longDescription',
            field=models.TextField(null=True),
        ),
    ]
