# Generated by Django 4.2.1 on 2023-05-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_pizza_longdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='longDescription',
            new_name='long_description',
        ),
    ]
