# Generated by Django 4.2 on 2023-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priceSmall', models.IntegerField()),
                ('priceMedium', models.IntegerField()),
                ('priceLarge', models.IntegerField()),
                ('spicy', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('desert', models.BooleanField()),
                ('popular', models.BooleanField()),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('toppings', models.ManyToManyField(to='home.toppings')),
            ],
        ),
    ]
