# Generated by Django 4.2 on 2023-05-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_pizza_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
