# Generated by Django 4.2 on 2023-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadsticks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sodas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TwoForOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('breadsticks', models.ManyToManyField(to='offers.breadsticks')),
                ('pizzas', models.ManyToManyField(to='menu.pizza')),
                ('soda', models.ManyToManyField(to='offers.sodas')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('breadsticks', models.ManyToManyField(to='offers.breadsticks')),
                ('pizzas', models.ManyToManyField(to='menu.pizza')),
                ('soda', models.ManyToManyField(to='offers.sodas')),
            ],
        ),
        migrations.CreateModel(
            name='LunchOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('breadsticks', models.ManyToManyField(to='offers.breadsticks')),
                ('pizzas', models.ManyToManyField(to='menu.pizza')),
                ('soda', models.ManyToManyField(to='offers.sodas')),
            ],
        ),
    ]
