# Generated by Django 4.2.1 on 2023-05-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_longdescription_pizza_long_description'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twoforone',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='twoforone',
            name='pizza1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza1', to='menu.pizza'),
        ),
        migrations.AddField(
            model_name='twoforone',
            name='pizza2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza2', to='menu.pizza'),
        ),
    ]
