# Generated by Django 4.2.1 on 2023-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_specialoffer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchoffer',
            name='description',
            field=models.TextField(default='Pizza and soda - great value, great taste.'),
        ),
        migrations.AlterField(
            model_name='lunchoffer',
            name='image',
            field=models.CharField(default='https://i.ibb.co/0jJQY1Q/Lunch-offer.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='lunchoffer',
            name='name',
            field=models.CharField(default='Lunch Offer', max_length=100),
        ),
        migrations.AlterField(
            model_name='lunchoffer',
            name='price',
            field=models.IntegerField(default=2490),
        ),
        migrations.AlterField(
            model_name='twoforone',
            name='description',
            field=models.TextField(default='Two pizzas for the price of one - great value, great taste.'),
        ),
        migrations.AlterField(
            model_name='twoforone',
            name='image',
            field=models.CharField(default='https://i.ibb.co/4SNhHp0/2-for-1.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='twoforone',
            name='name',
            field=models.CharField(default='Two for One', max_length=100),
        ),
        migrations.AlterField(
            model_name='twoforone',
            name='price',
            field=models.IntegerField(default=3990),
        ),
    ]
